# Generated by Django 3.1.2 on 2021-01-23 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210119_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popular',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
